### ISSUE TITLE
check in

### ISSUE THREAD

**Issue by dibrinsofor** [Nnamdi600000/Hungry_Lab#1]
is this for your final project?

**Comment by Nnamdi600000** [comment]
No. Not at all am still brushing up my skills for the final year one, that one would have a more clean architecture and a bit complex.

**Comment by Nnamdi600000** [comment]
Please follow back on github

**Comment by dibrinsofor** [comment]
i feel you, my guy, don't' overthink it sha.

**Comment by Nnamdi600000** [comment]
Okay bro
Thanks a lot

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
